# Generated by Django 4.0.6 on 2022-07-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookNo', models.IntegerField(primary_key=True, serialize=False, verbose_name='BOOK NUMBER')),
                ('BookName', models.CharField(max_length=200, verbose_name='BOOK NAME')),
                ('AuthorName', models.CharField(max_length=200, verbose_name='NAME OF AUTHOR')),
                ('PublisherName', models.CharField(blank=True, max_length=200, null=True, verbose_name='NAME OF PUBLISHER')),
                ('CostofBook', models.IntegerField(blank=True, null=True, verbose_name='COST OF BOOK')),
                ('DateofEntry', models.DateField(blank=True, null=True, verbose_name='DATE OF ENTRY')),
                ('StatusofBook', models.CharField(max_length=50, verbose_name='STATUS OF BOOK')),
                ('SourceofBook', models.CharField(blank=True, max_length=200, null=True, verbose_name='SOURCE OF BOOK')),
                ('RackNo', models.IntegerField(blank=True, null=True, verbose_name='RACK NUMBER')),
                ('Category', models.CharField(blank=True, max_length=200, null=True, verbose_name='CATEGORY')),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=200)),
                ('Count', models.IntegerField()),
            ],
        ),
    ]
