# Generated by Django 4.0.6 on 2022-08-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIB', '0002_count_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CATEGORY'),
        ),
        migrations.AlterField(
            model_name='book',
            name='CostofBook',
            field=models.IntegerField(blank=True, null=True, verbose_name='COST OF BOOK'),
        ),
        migrations.AlterField(
            model_name='book',
            name='PublisherName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='NAME OF PUBLISHER'),
        ),
        migrations.AlterField(
            model_name='book',
            name='RackNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='RACK NUMBER'),
        ),
        migrations.AlterField(
            model_name='book',
            name='SourceofBook',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SOURCE OF BOOK'),
        ),
        migrations.AlterField(
            model_name='book',
            name='StatusofBook',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='STATUS OF BOOK'),
        ),
    ]
