# Generated by Django 4.0.6 on 2022-08-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIB', '0003_alter_book_category_alter_book_costofbook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='Book',
            field=models.ManyToManyField(to='LIB.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='CostofBook',
            field=models.FloatField(blank=True, null=True, verbose_name='COST OF BOOK'),
        ),
    ]
