# Generated by Django 4.0.6 on 2022-08-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIB', '0004_count_book_alter_book_costofbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='AuthorName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='NAME OF AUTHOR'),
        ),
    ]
